project:
  type: book
  output-dir: docs

book:
  title: "R Lernplattform"
  author: "Methods Group Berlin"
  favicon: figures/Logo_Favicon.png
  chapters:
    - index.qmd
    - part: "R Crash Course"
      chapters:
        - Quick_Start_Installation.qmd
        - Einfuehrung_in_RStudio.qmd
        - R_als_Taschenrechner.qmd
        - Skripte.qmd
        - Datentypen.qmd
        - Vektoren.qmd
        - Matrizen.qmd
        - data_frames.qmd
        - Logische_Operatoren.qmd
        - Funktionen.qmd
        - Pakete.qmd
        - Fehler.qmd
    - part: Datenverarbeitung und Analyse
      chapters:
        - Daten-importieren.qmd
        - Datenvorbereitung.qmd
        - Fehlende-Werte.qmd
        - Grafiken.qmd
        - Fehlermeldungen.qmd
    - part: "Weiterführende Themen in R"
      chapters:
        - Installation.qmd
        - Wide-and-Long-Format.qmd
        - Markdown.qmd
        - Git.qmd
    - part: "Vertiefungen zu den Veranstaltungen Methodenlehre I und II"
      chapters:
        - Missings.qmd
        - Voraussetzungspruefung.qmd
        - Outputs-ALM-FAQ.qmd
    - part: "Projekt-Dokumentation"
      chapters:
        - Zur-Lernplattform-Beitragen.qmd
bibliography: references.bib

format:
  html:
    theme: [cosmo, style.scss]
    prefer-html: true
