project:
  type: book
  output-dir: docs

book:
  title: "R Lernplattform"
  author: "Methods Group Berlin"
  chapters:
    - index.qmd
    - part: "Einführung in R"
      chapters:
        - Installation.qmd
        - Einfuehrung_in_R.qmd
        - Einfuehrung_in_RStudio.qmd
        - Pakete.qmd
        - Daten-importieren.qmd
        - Fehlermeldungen.qmd
        - Datenvorbereitung.qmd
        - Fehlende-Werte.qmd
        - Grafiken.qmd
     - part: "Weiterführende Themen in R"    
        - Wide-and-Long-Format.qmd
        - Markdown.qmd
        - Git.qmd
    - part: "Vertiefungen zu den Veranstaltungen Methodenlehre I und II"
      chapters:
        - Voraussetzungspruefung.qmd
        - Outputs-ALM-FAQ.qmd
    - part: "Projekt-Dokumentation"
      chapters:
        - Interne-Dokumentation.qmd
        - lineare-regression.qmd
bibliography: references.bib

format:
  html:
    theme: [cosmo, style.scss]
  pdf:
    documentclass: scrreport
  epub:
    cover-image: cover.png
