# The following builds on:
# https://medium.com/@delucmat/how-to-publish-bookdown-projects-with-github-actions-on-github-pages-6e6aecc7331e
# https://quarto.org/docs/publishing/github-pages.html#executing-code

name: create_website

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  bookdown:
    runs-on: ${{ matrix.os }}
    name: ${{ matrix.os }} (${{ matrix.r-version }})

    strategy:
      matrix:
        r-version: ['release']
        os: ['windows-latest']

    steps:
      - uses: actions/checkout@v2
      - name: Set up R ${{ matrix.r-version }}
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.r-version }}
      - name: Set up pandoc
        uses: r-lib/actions/setup-pandoc@v2
      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
      - name: Install dependencies and create book
        run: |
          options(pkgType = "win.binary")
          options(install.packages.compile.from.source = "never")
          install.packages(c("quarto", "devtools", "renv"))
          renv::restore() # install packages in version defined by renv
          #devtools::install_deps(upgrade = "never")
        shell: Rscript {0}
      - name: Render and Publish
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
