# The following builds on:
# https://medium.com/@delucmat/how-to-publish-bookdown-projects-with-github-actions-on-github-pages-6e6aecc7331e
# https://quarto.org/docs/publishing/github-pages.html#executing-code

name: create_website

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  # Step 1: check if any of the dependencies did change and update the 
  # Docker image
  update-docker-image:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
         
    steps:
      - name: Check out code
        uses: actions/checkout@v3
        
      - name: Update Docker with Dependencies
        run: |
          ls && docker build . --file .github/workflows/update_image/Dockerfile --tag ghcr.io/methods-berlin/rlernplattform_dep:latest
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u $ --password-stdin
          docker push ghcr.io/methods-berlin/rlernplattform_dep:latest   
  
  # next: create website using docker
  bookdown:
    needs: update-docker-image
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/methods-berlin/rlernplattform_dep:latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      # Copied from oalders at https://github.com/actions/checkout/issues/1049
      - name: Allow for file ownership conflicts with Docker and GitHub Actions
        run: git config --global --add safe.directory '*'
      - name: Set git credentials
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
      - name: Set up pandoc
        uses: r-lib/actions/setup-pandoc@v2
      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
      - name: install rmarkdown
        run: install.packages("rmarkdown")
        shell: Rscript {0}
      - name: Render and Publish
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
