name: create-docker-image

# Only run this when the main branch changes
on:
  workflow_dispatch

jobs:

  create-docker-image:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
      
    steps:
      - name: Check out code
        uses: actions/checkout@v3
        
      - name: Build Docker with Dependencies
        run: |
          ls && docker build . --file .github/workflows/create_image/Dockerfile --tag ghcr.io/methods-berlin/rlernplattform_dep:latest
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u $ --password-stdin
          docker push ghcr.io/methods-berlin/rlernplattform_dep:latest
