# The following builds on:
# https://medium.com/@delucmat/how-to-publish-bookdown-projects-with-github-actions-on-github-pages-6e6aecc7331e

# NOTE: The page is currently created but not uploaded anywhere! If you want to see the 
# page, go to "Actions", click on "create_book" and scroll down until you see "Artifacts".
# There will be an artifact called "_book". This is our webpage. Download the file and 
# unzip it. Double-Clicking on any of the .html files will open the website locally.


name: create_book

on:
  workflow_dispatch

permissions:
  contents: write
  
jobs:
  bookdown:
    runs-on: ${{ matrix.os }}
    name: ${{ matrix.os }} (${{ matrix.r-version }})
    
    strategy:
      matrix:
        r-version: ['release']
        os: ['windows-latest'] 

    steps:
      - uses: actions/checkout@v2
      - name: Set up R ${{ matrix.r-version }}
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.r-version }}
      - uses: r-lib/actions/setup-pandoc@v2
      - name: Install dependencies and create book
        run: |
          options(install.packages.compile.from.source = "never")
          install.packages(c("rmarkdown", "bookdown", "devtools"))
          devtools::install_deps()
          bookdown::render_book("index.Rmd")
        shell: Rscript {0}
      - uses: actions/upload-artifact@v3
        with:
          name: _book
          path: _book/
      - name: Deploy website
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: _book
